version: "3.9"

volumes:
   ipfs:

services:

  Reese:
    image: lang/reese
    build:
      context: ./Lang/Reese
    ports:
      - 3311:8080
    depends_on:
      - Sarah-Connor

  Biehn:
    image: lang/biehn
    build:
      context: ./Lang/Biehn
    ports:
      - 3312:80

  Sarah-Connor:
    image: lang/Sarah-Connor
    build:
      context: ./Lang/Sarah-Connor
    volumes:
      - ipfs:/data/ipfs

  Boen:
    image: mariadb
    command: --max-allowed-packet=256M
    environment:
      MYSQL_DATABASE: wikipedia
      MYSQL_USER: wikipedia
      MYSQL_PASSWORD: wikipedia
      MYSQL_ROOT_PASSWORD: wikipedia

  Silberman:
    image: mediawiki
    ports:
      - 8000:80
    depends_on:
      - Boen