version: "3.9"

volumes:
   sarah-connor:
   boen:
  #  silberman-images:


services:

  Reese:
    image: lang/reese
    build:
      context: ./Lang/Reese
    ports:
      - 3311:8080
    depends_on:
      - Sarah-Connor

  Sarah-Connor:
    image: lang/sarah-connor
    build:
      context: ./Lang/Sarah-Connor
    volumes:
      - sarah-connor:/data/ipfs

  Boen:
    image: mariadb
    command: --max-allowed-packet=256M
    environment:
      MYSQL_DATABASE: wikipedia
      MYSQL_USER: wikipedia
      MYSQL_PASSWORD: wikipedia
      MYSQL_ROOT_PASSWORD: wikipedia
    volumes:
      - boen:/var/lib/mysql

  Silberman:
    image: lang/silberman
    build:
      context: ./Lang/Silberman
    ports:
      - 8000:80
    depends_on:
      - Boen
    links:
      - Boen
    # volumes:
    #   - silberman-images:/var/www/html/images
    #   - ./Lang/Silberman/LocalSettings.php:/var/www/html/LocalSettings.php
    #   - ./Lang/Silberman/extensions/TemplateStyles:/var/www/html/extensions/TemplateStyles
    #   - ./Lang/Silberman/extensions/Scribunto:/var/www/html/extensions/Scribunto
    #   - ./Lang/Silberman/php.ini:/usr/local/etc/php/conf.d/mediawiki.ini
